global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['34.148.204.82:8080']

  - job_name: 'GymSprint'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['34.30.181.186:9100']
